DROP TABLE IF EXISTS users;

CREATE TABLE users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(64),
    email VARCHAR(64) NOT NULL,
    login VARCHAR(64) NOT NULL,
    birthday DATE NOT NULL
);

DROP TABLE IF EXISTS friends;

CREATE TABLE friends (
    request_friend_id INTEGER REFERENCES users(user_id) ON UPDATE RESTRICT ON DELETE CASCADE,
    response_friend_id INTEGER REFERENCES users(user_id) ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT FRIENDS_PK PRIMARY KEY (request_friend_id, response_friend_id)
);

DROP TABLE IF EXISTS films;

CREATE TABLE IF NOT EXISTS films (
   film_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   film_name VARCHAR(128) NOT NULL,
   description VARCHAR(256),
   release_date DATE,
   duration INTEGER,
   rate INTEGER,
);

